version: '3.8'

services:
  
  # web:
  #   build: .
  #   command: python /code/spam_recycler/manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  
  db:
    container_name: "database"
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  rabbitmq:

    container_name: "rabbitmq"
    
    image: rabbitmq:3.9.11-management
    
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI port
      - '15672:15672'
    
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      
    volumes:
      # Users/Password/Vhosts configuration files
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    
volumes:
  postgres_data:
