version: '3.8'

services:
  
  web-app:
    build: .
    command: supervisord -c /code/supervisor.conf
    ports:
      # App
      - 8000:8000
      # Flower
      - 5000:5000
    
    environment:
      # RabbitMQ credentials
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      # Django settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      # Postgres credentials
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      # Spamassasin
      - SPAMASSASIN_HOST=${SPAMASSASIN_HOST}
      - SPAMASSASIN_PORT=${SPAMASSASIN_PORT}
    
    depends_on:
      - rabbitmq
      - db
      - spamassasin

  db:
    container_name: "db"
    image: postgres:13-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  
  spamassasin:
    container_name: "spamassasin"
    build:
      context: ./spamassasin
      dockerfile: Dockerfile
    
    ports:
      # SPAMD protocol port
      - '9000:9000'
    environment:
      - HOST=${SPAMASSASIN_HOST}
      - PORT=${SPAMASSASIN_PORT}


  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.9.11-management
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI port
      - '15672:15672'
    
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      
    volumes:
      # Users/Password/Vhosts configuration file
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    
volumes:
  postgres_data:
