# Generated by Django 3.1.4 on 2021-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20211128_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='orginal_message',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
    ]
