# Generated by Django 3.1.4 on 2021-11-26 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxGuestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mailbox_guest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailboxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=32)),
                ('server_address', models.CharField(max_length=255)),
                ('guests', models.ManyToManyField(related_name='guest_mailbox', through='mailboxes.MailboxGuestModel', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email_address', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='mailboxguestmodel',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_mailbox', to='mailboxes.mailboxmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxguestmodel',
            unique_together={('guest', 'mailbox')},
        ),
    ]
